version: '3'
services:
  azulito-pg:
    image: postgres:14
    container_name: azulito-pg
    privileged: true
    environment:
        - POSTGRES_DB=trade
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trade"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s

  azulito-back:
    container_name: azulito-back
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      azulito-pg:
        condition: service_healthy
    restart: on-failure 
    ports:
      - 8080:8080
    environment:
      - REPORT_FOLDER=./reports_tmp

  azulito-front:
    container_name: azulito-front
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - azulito-pg
      - azulito-back
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 3000:3000
