CREATE TABLE USUARIO (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);

CREATE TABLE ALBUM (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    year INT NOT NULL
);

CREATE TABLE USUARIO_TIENE_ALBUM (
    id_usuario INT NOT NULL REFERENCES USUARIO,
    id_album INT NOT NULL REFERENCES ALBUM,
    PRIMARY KEY (id_album, id_usuario)
);

CREATE TABLE BARAJITA (
    id SERIAL,
    id_album INT REFERENCES ALBUM,
    player_name VARCHAR(50) NOT NULL,
    cost INT NOT NULL,
    country VARCHAR(50) NOT NULL,
    position VARCHAR(50) NOT NULL,
    PRIMARY KEY (id, id_album)
);

CREATE TABLE USUARIO_POSEE_BARAJITA (
    id_usuario INT NOT NULL REFERENCES USUARIO,
    id_album INT NOT NULL REFERENCES ALBUM,
    id_barajita INT NOT NULL REFERENCES BARAJITA,
    visibilidad BOOLEAN NOT NULL,
    quantity INT NOT NULL,
    PRIMARY KEY (id_album, id_barajita, id_usuario)
);

CREATE TYPE BARAJITA_ID_LIST AS INT[];

CREATE TABLE TRADE (
    id SERIAL PRIMARY KEY,
    id_usuario_offer INT NOT NULL REFERENCES USUARIO,
    id_usuario_recieve INT NOT NULL REFERENCES USUARIO,
    id_album_offer INT NOT NULL REFERENCES ALBUM,
    id_album_recieve INT NOT NULL REFERENCES ALBUM,
    id_barajitas_offer BARAJITA_ID_LIST NOT NULL,
    id_barajitas_recieve BARAJITA_ID_LIST NOT NULL,
    status VARCHAR(50) NOT NULL
);
