# Configuraci贸n de la base de datos PostgreSQL
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://azulito-pg:5432/trade-db
    username: azulito
    password: azul
    driver-class-name: org.postgresql.Driver

# Configuraci贸n de Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

# Configuraci贸n de Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://azulito-pg:5432/trade-db
    user: azulito
    password: azul

# Configuraci贸n de Google y Facebook OAuth
  security:
    oauth2:
      client:
        registration:
        #   google:
        #     client-id: 299136953332-pp4ndg7v43dmh5e16bnb5k2q4m1jm0ko.apps.googleusercontent.com
        #     client-secret: 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
        #     scope:
        #         - email
        #         - profile
            facebook:
              clientId: 1462257131030960
              clientSecret: f10eba43950fdb5e1c367732c5e4e7b1
              scope:
                - email
                - public_profile